vmware/liota

MANIFEST.in, requirements.txt, setup.py
Proper configuration of Setup.py to use MANIFEST.in and requirements.txt
=> Proper configuration of Setup.py

example/graphite_event_based.py, example/graphite_simulated.py, example/graphite_withTemp.py, example/vrops_graphite_DellEdge5K_sample.py, example/vrops_graphite_dk300_sample.py, liota/boards/gateway.py, liota/boards/gateway_de5000.py, liota/boards/gateway_dk300.py, liota/dcc/dcc_base.py, liota/dcc/graphite_dcc.py, liota/dcc/vrops.py, setup.py
1. Registration of Gateway is introduced for each DCC component.
2. SetProperties has been made specific to vROPS DCC rather than associated with Gateway
=> Gateway registration made specific to DCC

MANIFEST.in, README.md, config/liota.conf, liota/__init__.py, setup.py
PIP issue resolved 
Log folder creation in python code
Manifest update
=> PIP issue resolved, Log folder creation & Manifest update

example/sampleProp.conf, example/vrops_graphite_DellEdge5K_sample.py, example/vrops_graphite_dk300_sample.py, example/vrops_simulated.py, liota/dcc/vrops.py
1) Removed unnecessary sleep call in vROps registration.
2) Changed addition of properties to a single call, instead of one call
for each property.
=> Optimized vROPs DCC

config/liota.conf, liota/__init__.py, liota/dcc/vrops.py, liota/utilities/utility.py
Storing UUID locally at the gateway in uuid.ini file (location /etc/liota/conf) to be used by other agents.
=> Storing UUID locally at Gateway to be used by other agents

liota/dcc/vrops.py
Gateway name with uuid made part of the uuid.ini file
=> Gateway name made part of the uuid.ini file

liota/core/metric_handler.py, liota/dcc/dcc_base.py, liota/dcc/graphite_dcc.py, liota/dcc/vrops.py
changed for both vrops and graphite;
also fixed current_aggregation_size reset issue: 
now in collection thread, when send_queue.put(matric), reset that conter.
=> modifying metric values storage from list to queue

examples/multi_metric_simulated_system_graphite.py, examples/sampleProp.conf, liota/core/metric_handler.py, liota/dcc_comms/socket_comms.py, liota/entities/metrics/registered_metric.py, setup.py
Modified Metric Handler to return either of the following:
1) Metric Value
2) Metric value along with a time stamp
3) A list of metric values along with timestamps
=> Sampling function returning timestamp or multiple values optionally

config/liota.conf, examples/dell5k_system_graphite.py, examples/model_simulated/graphite_bike_simulated.py, examples/model_simulated/graphite_thermistor_simulated.py, examples/sampleProp.conf, liota/__init__.py, liota/core/metric_handler.py, liota/core/package_manager.py, liota/dccs/dcc.py, liota/dccs/graphite.py, liota/entities/devices/bike_simulated.py, liota/entities/devices/device.py, liota/entities/devices/thermistor_simulated.py, liota/entities/entity.py, liota/entities/metrics/metric.py, liota/entities/metrics/registered_metric.py, liota/entities/registered_entity.py, liota/entities/systems/dell5k_system.py, liota/entities/systems/simulated_system.py, liota/entities/systems/system.py, packages/examples/bike_simulator.py, packages/examples/graphite_bike_simulated.py, packages/examples/graphite_system_stats.py, packages/examples/graphite_thermistor_simulated.py, packages/examples/thermistor_simulator.py, packages/graphite.py, packages/liotapkg.sh, packages/sampleProp.conf, packages/systems/dell5k/system.py, setup.py
1. change graphite to use a common register call for system/device/metric
2. use autopep8 as formatting tool (did for all checkedin codes)
3. inside liota/__init__.py file, use setup_package for configuration
for package manager
4. other modifications based on commnents
=> Add modifications based on review comments

examples/dell5k_edge_system_graphite.py, examples/dell5k_edge_system_iotcc.py, examples/dk300_edge_system_iotcc.py, examples/model_simulated/graphite_bike_simulated.py, examples/model_simulated/graphite_thermistor_simulated.py, examples/multi_metric_simulated_edge_system_graphite.py, examples/simulated_edge_system_graphite.py, liota/dccs/dcc.py, liota/dccs/iotcc.py, liota/lib/transports/web_socket.py, packages/examples/bike_simulator.py, packages/examples/graphite_bike_simulated.py, packages/examples/graphite_edge_system_stats.py, packages/examples/graphite_thermistor_simulated.py, packages/examples/iotcc_bike_simulated.py, packages/examples/iotcc_edge_system_stats.py, packages/examples/iotcc_ram.py, packages/examples/iotcc_thermistor_simulated.py, packages/examples/thermistor_simulator.py, packages/graphite.py, packages/iotcc.py
1. Add RegistrationFailure(Exception) class; use it in iotcc registration call
2. Provide an example to show how to catch RegistrationFailure exception
3. Remove condition check in examples
=>  Add Registration Failure Process

README.md, liota/dccs/iotcc.py, liota/lib/transports/web_socket.py, packages/README.md
Details have to be changed in Readme.md
=> Added Readme.md & fixed the conditional check

README.md, config/liota.conf, examples/model_simulated/README.md, packages/README.md, packages/edge_systems/README.md
=> Small changes in README.md

examples/dell5k_edge_system_iotcc.py, examples/dell5k_edge_system_with_filter_iotcc.py, examples/dk300_edge_system_iotcc_graphite.py, liota/lib/utilities/filters/range_filter.py, liota/lib/utilities/filters/windowing_scheme/windowing_scheme.py, packages/examples/graphite_edge_system_stats.py, packages/examples/graphite_edge_system_stats_with_filter.py, packages/examples/iotcc_edge_system_stats.py, setup.py
Fix for #78
----------- 
- eth0 > ens33
- log.info > log.debug
- `ValueError` > `TypeError`
- Applying Windowing scheme to `CPUUtil` instead of Network Util
=> Filter with Graphite

liota/core/device_discovery.py
1. form a relationship between newly discovered device and gateway
2. update the organization group property for the newly discovered device
=> Add supports in the device discovery:

packages/liotad/liotapkg.sh
add a check in the liotapkg.sh to see if liota is running
before writing commands into named pipe
=> Package Manager Improvement:

examples/mqtt/README.md, liota/dcc_comms/mqtt_dcc_comms.py, liota/dccs/iotcc.py, liota/lib/transports/mqtt.py, packages/user_packages/README.md, packages/user_packages/iotcc_mqtt.py, packages/user_packages/iotcc_mqtt_edge_system_stats.py
1. MQTT Topic re-subscribe mechanism on reconnect
2. Refactoring MQTT, MQTT_DCC_COMMS
3. Unsubscribe implementation in MQTT
4. Updated comments and README
=> Re-subscribe mechanism

liota/core/metric_handler.py, liota/entities/metrics/registered_metric.py, liota/lib/transports/mqtt.py, packages/user_packages/README.md, packages/user_packages/iotcc_mqtt.py, packages/user_packages/iotcc_mqtt_edge_system_stats.py
1. Raise exception from transports mqtt layer.
2. Improve & Correct metric_handler and registered_metric to handle exceptions properly.
=> Handling Exception

liota/dccs/dcc.py, liota/dccs/iotcv2.py, packages/user_packages/iotcv2/iotcv2_ecus.py, packages/user_packages/iotcv2/iotcv2_edge_system.py, packages/user_packages/iotcv2/iotcv2_toyota_sim.py, packages/user_packages/iotcv2/iotcv2_wssl.py, packages/user_packages/iotcv2/iotcv2_wssl_metrics.py, packages/user_packages/iotcv2/sampleProp.conf, packages/user_packages/iotcv2/sampleProp.yml
1. add a DCC for VMware IoTC V2 Data Center Component, which has
blocking call for Managed Object register, set properties, and
create relationship operations (multithread handling support)
2. modify dcc.py to add Exception class for set properties and
create relationship
3. add example liota packages for IoTC V2 under "packages/
user_packages/iotcv2" folder
=> Add liota V2 features:

liota/core/metric_handler.py, liota/core/package_manager.py, liota/entities/metrics/metric.py, liota/entities/metrics/registered_metric.py, liota/lib/utilities/si_unit.py, liota/lib/utilities/utility.py, packages/liotad/cal_sha1sum.py, packages/liotad/liotad.py
metric_handler.py, package_manager.py, metric.py, registered_metric.py, si_unit.py, liotad.py,
cal_sha1sum.py and utility.py.
=> Add documents for modules:

liota/dcc_comms/dcc_comms.py, liota/dcc_comms/socket_comms.py, liota/dcc_comms/websocket_dcc_comms.py, liota/dccs/dcc.py, liota/dccs/graphite.py, liota/device_comms/device_comms.py, liota/device_comms/mqtt_device_comms.py, liota/entities/devices/bike_simulated.py, liota/entities/devices/device.py, liota/entities/devices/simulated_device.py, liota/entities/devices/thermistor_simulated.py, liota/entities/edge_systems/dell5k_edge_system.py, liota/entities/edge_systems/dk300_edge_system.py, liota/entities/edge_systems/edge_system.py, liota/entities/edge_systems/general_edge_system.py, liota/entities/edge_systems/simulated_edge_system.py, liota/entities/entity.py, liota/entities/metrics/metric.py, liota/entities/metrics/registered_metric.py, liota/entities/registered_entity.py, packages/aws_iot.py, packages/edge_systems/dell5k/edge_system.py, packages/graphite.py, packages/iotcc_mqtt.py, packages/user_packages/general_edge_system.py, packages/user_packages/iotcc_mqtt.py, packages/user_packages/iotcc_mqtt_edge_system_stats.py
Dcc_comms.py
Device_comms.py
Dcc.py
Device.py
Simulated_device.py
Edge_system.py
General_edge_system.py
Simulated_edge_system.py
Entity.py
Reg_entity.py
All the user_packages (general_edge_system.py, iotcc_mqtt.py, iotcc_mqtt_edge_system_stats.py)
Partly addressing #64
=> Added documentation for the following

liota-lite/setup.py, liota/dccs/iotcc.py, packages/user_packages/iotcc_mqtt_edge_system_stats.py, setup.py
Updated Code document for;
iotcc.py
setup.py
iotcc_mqtt_edge_system_stats.py
=> Updated Code Document 

config/liota.conf, liota/dccs/iotcc.py, packages/user_packages/iotcc_mqtt.py
Response check for relationship and properties call
=> Response for properties and relationship calls

config/liota.conf, liota/core/device_discovery.py, liota/core/discovery_simulator.py, liota/core/package_manager.py, liota/dev_sims/named_pipe.py, liota/disc_listeners/named_pipe.py, liota/lib/utilities/utility.py, packages/liotad/README.md, packages/liotad/liotapkg.sh
This reverts commit 29b719895221b53f14aa09dd1c801667b0b6586c, reversing
changes made to fb2009dead31d938986b3da73f34e4106da7b3b1.
#	liota/lib/utilities/utility.py
#	packages/liotad/liotapkg.sh
=> Revert "Merge pull request #191 from winniex1/get_property"

config/liota.conf, liota/lib/transports/mqtt.py
This pull request only handle the code changes to make the current mechanism of MQTT transport layer conn_disconn_timeout configurable.
=> Making MQTT Connect Disconnect Timeout configurable

README.md, packages/liotad/README.md
I have closed the previous pull request as it had merge conflict:
https://github.com/vmware/liota/pull/205
I'm raising this new pull request and have addressed the review comments from the previous PR.
=> Readme Updates

liota/dccs/iotcc.py
Set metric SI units with prefix
=> Set SI units with prefix

packages/user_packages/README.md, packages/user_packages/iotcc_mqtt.py, packages/user_packages/iotcc_mqtt_dev.py, packages/user_packages/iotcc_mqtt_device.py, packages/user_packages/iotcc_mqtt_edge_system_stats.py
In this PR user packages are updated as per the test results and the retry mechanism for important calls like registration, create_relationship & set_properties. 
The PR needs to be merged urgently for the release. The retry logic values were finalized today in the meeting. Major review comments will be addressed.
=> User Package Update

liota-lite/setup.py, setup.py
=> Version Bump in Liota

packages/examples/edgex/README.md, packages/examples/edgex/edgex_device.py
Integrate EdgeXFoundry into Liota
=> Edgexfoundry liota integration
